name: CI/CD Workflow

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  pre-commit-scans:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup java
      uses: actions/setup-java@v4
      with:
         distribution: 'temurin' 
         java-version: '21'

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check Setup
      run:  |
        java --version
        ls -ltr

    

    
